sudo: required
os: linux
language: python
python:
- 3.8
install:
- git clone https://github.com/kirainmoe/auto-daily-health-report healthreport
- cd healthreport
- pip install -r requirements.txt
script:
- python checkin.py ${xmu_username} ${xmu_password}
